package taxi;

import taxi.person.Customer;

public class Application {
	
	public static void main(String[] args) throws InterruptedException {

		Customer unknown = TaxiManager.getInstance().getCustomers().get(0);

		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OOkxkkO0KWMMMMMMMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOkkkkkkkkkkkxxO0XWMMMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xxk00K0000000K0OOkxkXMMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxdO000000000000000000kxONMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxxO000000OkkkkO00000000OxOWMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkd00000xolccccccldk00000KkdKMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxx00Od:,,;::clcllccok00000dOWMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0dO00d'......,,'''''.;k0000xkWMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOdOK0c.......''.'.....l000OdOWMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxk0Oc,,,,';:;,......'l000xdXMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxok0dclllcooloc::::;:x00OxOWMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;;:okxl:cllllccllllccx00kdONMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;'.'cl;..,:ccclcc;;cdkkkkKWMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxllllddxdolllo0WMMMMMMXl,'........,,.......:OXNWMMMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWKc.....,ld:.....'xNNWWNOo,,,;c:..............'kWWWWWWWMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMWWNNXK0OOkkkOkkkkkkkkkkkkkkkkkkkkkkkOkOx:.......,;'......'okOxc;;::,;dd'......,'.....,dOkOOO0XXNNWMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMWNXKOkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxkkkkxkkkkxkkkxxxxxxxxxxxxxxkkkkkkkkkxk0XNWWMMMMMMMM\r\n"
				+ "MMMMMMMWNXKkxxO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0k0KKKKK0kxxOXXWMMMMMMM\r\n"
				+ "MMMMMMWXKOdx0KKKKKKK0O0KKKK00KKKKKKKKK0kOKKKKKKKKKKKKKKKKKKKKKKKKKKkooooooooox0KKKKKKKKKKKKKKKKKKxcdKKKKKKKKkdk0XNWMMMMM\r\n"
				+ "MMMMMWXKOdkKKKKKKKKKx:dKK0dcxKKKK000KKk:l0KKKKKKKK000KKKKK0000KKKKKkooo:,:loox0OkkO0KK0OOKKKKOk0K0O0KKKKKKKKK0dxKXNMMMMM\r\n"
				+ "MMMMWNK0dxKKKKKKKKKKx;d0xcck0KKkoooloOk:l0KxlxKKkoooloOK0dllolld0KKKKKKo,l0KKOlccc:lOKOl;oO0x::x0d:d0KKKKKKKKKOdkKXWMMMM\r\n"
				+ "MMMMNXKxd0KKKKKKKKKKx;oo:o0KKKKOkkko;ok:lklcd0KKOkkko:d0o:x000x:l0KKKK0o,l0KK0xddo:,oKKOo::c;ckKKo,l0KKKKKKKKKKkdOKXWMMM\r\n"
				+ "MMMWXKkd0KKKKKKKKKKKx;odclkKKKOlclol;ok:cc;dKKKklclol;ok:l0K0K0l:kKKKKKo,l0K0o;:cl:,oKKKkc,,;d0KKo,l0KKKKKKKKKKKkd0XNWMM\r\n"
				+ "MMWXKkdOKKKKKKKKKKKKx:dKOocoOKd;oOko;ok:lOdcoOKo;oOko;o0o:okOOd:o0KKKK0o,l0Kk;;oxdc,o00d:;oxc;lk0o,l0KKKKKKKKKKK0xd0XNMM\r\n"
				+ "MWNKOdkKKKKKKKKKKKKKklxKKKkox0OdlooookOod0KkoxKOdlloookK0xolllox0KKKKKKxld0K0xc:ccllxKOookKK0dlx0xlx0KKKKKKKKKKKK0dxKXWM\r\n"
				+ "MNX0dx0KKKKKKKKKKKKKK0KKKKKKKKKKK0KKKKKKKKKKKKKKKKKKKKKKKKK00KKKKKKKKKKKKKKKKK0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOokKXW\r\n"
				+ "WXKxlxOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooOKN\r\n"
				+ "NK0xoddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddOKX");
		Thread.sleep(3000);
		
		System.out.println("[Customer]");
		System.out.println(unknown.toString());
		
		Thread.sleep(2000);;

		unknown.callTaxi();
		//yoo.checkMenu();
		
		
		
}
}
